### ISSUE TITLE
Adding More Snippets for CSS

### ISSUE THREAD

**Issue by Ritwik880** [30-seconds/30-seconds-of-css#184]
1. Media Queries for Standard Devices
2. Lazy loading images
3. Remove duplicates from an array

**Comment by skatcat31** [comment]
What do you mean by removing duplicates from an array?

**Comment by Ritwik880** [comment]
Removing items from an array, especially if those items are arrays themselves.

 const array = [1, 1, 1, 3, 3, 2, 2];

const unique = [...new Set(array)];
 

const unique = array.reduce((result, element) => {
  return result.includes(element) ? result : [...result, element];
}, []);
 

const unique = array.filter((element, index) => {
  return array.indexOf(element) === index;
});

**Comment by skatcat31** [comment]
That's JavaScript, not CSS

**Comment by Ritwik880** [comment]
What about  the other two?

**Comment by Chalarangelo** [comment]
> 1. Media Queries for Standard Devices

We have discussed this in the past, we will not be implementing this as what is considered standard devices changes quite often. Additionally, the idea of a standard device media query is somewhat outdated as developers are encouraged to develop with features in mind, instead of limiting themselves to standard device media querying.

> 2. Lazy loading images

This one might be more suited for a blog post than anything else, as it requires some explaining and details that might not fit well in the snippet format.

> 3. Remove duplicates from an array

JS snippet, already implemented as uniqueElements.
