### ISSUE TITLE
Snippet structure & philosophy

### ISSUE THREAD

**Issue by atomiks** [30-seconds/30-seconds-of-css#30]
This issue is about the design/structure of snippets and their content.

- Some snippets' HTML/CSS code does not line up with the demo. I made it that way so that I could include the bare minimum CSS needed to create an effect, but this has the problem of not matching the demo and not being reproducible if they copy/paste the code. How should this be handled?

- Should the browser support have an automagic button that converts the code into the widest browser support possible so a user can copy/paste it?

- Live editing. #4 should be coming soon

**Comment by Chalarangelo** [comment]
I do believe the project could do with some more in-depth contribution guidelines, especially addressing these issues. My opinion on these specific points is as follows:

- The provided snippet code should be the bare minimum to use the concept/design in a project. It does not matter if it does not actually show anything if copied to an empty project, many of the snippets create containers or designs that can be reusable and content-dependent. Demos should contain some content to be able to show off how the snippet works. This includes customized containers (ie colored boxes), text or even images if necessary to prove that the snippet works and showcase the functionality.
- Browser support should not really be an issue, unless a snippet has support below 70%. In those cases, I think that the build process could be configured to notify us, so that proper notes can be added for such issues.
- I'd love to help out with live editing (I'll message you on Gitter).

**Comment by sinout** [comment]
A Few thoughts on this topic:

1. I agree with @Chalarangelo that
 > The provided snippet code should be the bare minimum to use the concept/design in a project. It does not matter if it does not actually show anything if copied to an empty project. 

  Also live editing of demo could be a good solution to see what effects are applied.

2. It is a good idea to have a simple copy button. But I don't think it should convert copied code as long as snippet contains "Browser support" section with links and warnings.

**Comment by Chalarangelo** [comment]
I'm gonna close due to inactivity. To add my final thoughs on this: 
* It's been a while since we had this discussion, but looking at the website and based on feedback from the community (or lack thereof), I think it's safe to say demo code is alright. 
* Live editing would only make the site heavier, Codepen links are more than fine imho.
* Low browser support hasn't been an issue and, based on the fact that the codebase is not growing that rapidly, we can personally check snippets that get merged into it and see if any of them raise any red flags in terms of support, so we can postpone merging them for a little while.
